[from-internal]
exten => 600,1,NoOp(Echo test)
 same => n,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => 700,1,NoOp(Playback test)
 same => n,Answer()
 same => n,Playback(demo-congrats)
 same => n,Hangup()

exten => 800,1,NoOp(Placeholder helpdesk intake extension)
 same => n,Answer()
 same => n,Playback(demo-thanks)
 same => n,Hangup()
